name: 'Delete from S3 Action'
description: 'Delete objects from S3 bucket'
inputs:
  aws_access_key_id:
    description: ''
    required: false
  aws_secret_access_key:
    description: ''
    required: false
  aws_bucket_name:
    description: 'aws bucket name'
    required: true

outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'