name: Upload to S3 Action pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - develop
permissions:
  id-token: write
  contents: write

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest
    environment: develop
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v3
    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: yarn
    - name: Install Dependencies
      id: yarn-ci
      run: yarn
    - name: Check Format
      id: yarn-format-check
      run: yarn format:check
    - name: Lint
      id: yarn-lint
      run: yarn lint
    - name: Test
      id: yarn-ci-test
      run: yarn ci-test
  code-analysis:
    name: SonarCloud Code Analysis
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: actions/checkout@v3.6.0
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@v2.0.0
        with:
          projectBaseDir: .
        env:
          GITHUB_TOKEN: ${{ secrets.PIPELINE_GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
