name: 'Post Release Tag Sync'
on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  sync-tag:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3.6.0
      - name: 'Setup Git'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global core.autocrlf input
      - name: 'Merge Main to Next'
        shell: bash
        run: |
          git checkout origin/main
          git pull origin main --allow-unrelated-histories
          git checkout origin/next
          git pull origin next 
          git merge main
          git push origin next --follow-tags
      - name: 'Merge Next to Develop'
        shell: bash
        run: |
          git checkout origin/develop
          git pull origin develop --allow-unrelated-histories
          git merge origin/next
          git push origin develop --follow-tags