name: Upload to S3 Action pipeline

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
permissions:
  id-token: write
  contents: write

jobs:
  code-analysis:
    environment: release
    name: SonarCloud Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/checkout@v3.6.0
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@v2.0.0
        with:
          projectBaseDir: .
        env:
          GITHUB_TOKEN: ${{ secrets.PIPELINE_GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  release:
    name: generate-version
    runs-on: ubuntu-latest
    environment: release
    needs: code-analysis
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7.0.5
      - name: checkout
        uses: actions/checkout@v3.6.0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Set up environment
        if: |
          github.ref == 'refs/heads/develop' ||
          github.ref == 'refs/heads/next' ||
          github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{secrets.PIPELINE_GITHUB_TOKEN}}
        run: |
          yarn install
      - name: Generate App Version
        if: |
          github.ref == 'refs/heads/next' ||
          github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{secrets.PIPELINE_GITHUB_TOKEN}}
        shell: bash
        run: bash ./scripts/generate-version.sh ${{ steps.branch-name.outputs.current_branch }}
